### ISSUE TITLE
load_from_beginning is fail when consumer group information is not exist in Kafka

### ISSUE THREAD

**Issue by sasakitoa** [sasakitoa/embulk-input-kafka#5]
`load_from_beginning` option will fail when consumer group information is not exists in Kafka.

Error mesage is below.

> java.lang.IllegalStateException: No current assignment for partition topic1-0
> 	at org.apache.kafka.clients.consumer.internals.SubscriptionState.assignedState(SubscriptionState.java:264)
> 	at org.apache.kafka.clients.consumer.internals.SubscriptionState.needOffsetReset(SubscriptionState.java:336)
> 	at org.apache.kafka.clients.consumer.KafkaConsumer.seekToBeginning(KafkaConsumer.java:1218)
> 	at org.embulk.input.kafka.KafkaInputPlugin.setOffsetPosition(KafkaInputPlugin.java:138)
> 	at org.embulk.input.kafka.KafkaInputPlugin.run(KafkaInputPlugin.java:101)
> 	at org.embulk.exec.PreviewExecutor$2$1.run(PreviewExecutor.java:141)
> 	at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:96)
> 	at org.embulk.spi.util.Filters.transaction(Filters.java:49)
> 	at org.embulk.exec.PreviewExecutor$2.run(PreviewExecutor.java:130)
> 	at org.embulk.input.kafka.KafkaInputPlugin.resume(KafkaInputPlugin.java:80)
> 	at org.embulk.input.kafka.KafkaInputPlugin.transaction(KafkaInputPlugin.java:75)
> 	at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:127)
> 	at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:114)
> 	at org.embulk.exec.PreviewExecutor.access$000(PreviewExecutor.java:31)
> 	at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:83)
> 	at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:79)
> 	at org.embulk.spi.Exec.doWith(Exec.java:25)
> 	at org.embulk.exec.PreviewExecutor.preview(PreviewExecutor.java:79)
> 	at org.embulk.EmbulkEmbed.preview(EmbulkEmbed.java:169)
> 	at org.embulk.EmbulkRunner.previewInternal(EmbulkRunner.java:247)
> 	at org.embulk.EmbulkRunner.preview(EmbulkRunner.java:119)
> 	at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:465)
> 	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:100)

In this case, I specified `topic1` for topic.

**Comment by sasakitoa** [comment]
In the case which consumer group information is not exists(the first time to load by this consumer group, for example), I should not specified `load_from_beginning`.

Maybe I must not use KafkaConsumer#seekToBeginning when consumer group info. isn't exists.
